### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MoonGoblinDev** [makercyf/syosetu-downloader#1]
```
F:\syosetu-downloader-1.3.0>syosetu.py
Library does not exist. Please create one first.
Please input the light novel library path: F:\syosetu-downloader-1.3.0\library
===== Menu =====
1. Display all books in the library
2. Add book to library
3. Remove book from library
4. Download the light novel from web
5. Update the light novel in the library
0. Exit the program
Your option: 2
URL: https://ncode.syosetu.com/n2959bs/
Successfully added 勇者パーティーにかわいい子がいたので、告白してみた。 to library.
===== Menu =====
1. Display all books in the library
2. Add book to library
3. Remove book from library
4. Download the light novel from web
5. Update the light novel in the library
0. Exit the program
Your option: 5
===== Update =====
Updating 勇者パーティーにかわいい子がいたので、告白してみた。
Traceback (most recent call last):
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 316, in <module>
    downloader.main()
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 288, in main
    self.menu()
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 243, in menu
    self.menu()
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 251, in menu
    self.update()
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 220, in update
    self.download(False, book["url"], True)
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 189, in download
    self.createIndexPage(novel_title, acn, last, writer_name, description, index)
  File "F:\syosetu-downloader-1.3.0\syosetu.py", line 114, in createIndexPage
    with open(f"{self.database_path}/{novel_title}/0. index.html", "w", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\syosetu-downloader-1.3.0\\library/勇者パーティーにかわいい子がいたので、告白してみた。/0. index.html'

F:\syosetu-downloader-1.3.0>
```

**Comment by makercyf** [comment]
Sorry, I forgot to publish the new release. The new release v1.3.1 should have already fixed this problem. Please download v1.3.1 and try again. Hope this message can solve your problem :)
(I also met this problem and I already fixed the bug in the past few days. However, I forgot to publish the latest version as a new release...)
